import React, { useRef } from "react";
import "./SalarySlip.css";

export default function SalarySlip({ user, month, attendance, totalEarned, totalPaid, pending, onClose }) {
  const slipRef = useRef();

  function handlePrint() {
    const content = slipRef.current.innerHTML;
    const win = window.open("", "_blank");
    win.document.write(`
      <html><head><title>Salary Slip</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 30px; color: #1a1a2e; }
        .slip-header { text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 20px; }
        .slip-header h1 { font-size: 22px; color: #4f46e5; margin: 0; }
        .slip-header p { font-size: 13px; color: #666; margin: 4px 0 0; }
        .slip-info { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; }
        .slip-info-item { background: #f8fafc; padding: 10px 14px; border-radius: 8px; }
        .slip-info-item label { font-size: 11px; color: #666; text-transform: uppercase; display: block; margin-bottom: 3px; }
        .slip-info-item span { font-size: 14px; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #4f46e5; color: white; padding: 10px 14px; text-align: left; font-size: 12px; }
        td { padding: 9px 14px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
        tr:nth-child(even) td { background: #f8fafc; }
        .slip-summary { background: #f0fdf4; border: 1px solid #6ee7b7; border-radius: 10px; padding: 16px 20px; }
        .slip-summary-row { display: flex; justify-content: space-between; padding: 5px 0; font-size: 14px; }
        .slip-summary-row.total { font-weight: 800; font-size: 16px; border-top: 1px solid #6ee7b7; margin-top: 8px; padding-top: 10px; }
        .green { color: #059669; } .orange { color: #d97706; }
        .slip-footer { text-align: center; margin-top: 24px; font-size: 12px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 14px; }
      </style></head><body>${content}</body></html>
    `);
    win.document.close();
    win.print();
  }

  function handleWhatsApp() {
    const msg = `*Salary Slip — ${month}*\n\nEmployee: ${user.name}\nCode: #${user.employeeCode}\nDays Present: ${attendance.length}\nTotal Earned: Rs. ${totalEarned.toLocaleString()}\nSalary Paid: Rs. ${totalPaid.toLocaleString()}\nPending: Rs. ${pending.toLocaleString()}\n\n_Generated by Attendance System_`;
    const url = `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, "_blank");
  }

  const [year, mon] = month.split("-");
  const monthName = new Date(year, mon - 1).toLocaleString("en-US", { month: "long", year: "numeric" });

  return (
    <div className="slip-overlay" onClick={onClose}>
      <div className="slip-modal" onClick={(e) => e.stopPropagation()}>
        <div className="slip-actions-top">
          <button className="slip-close" onClick={onClose}>✕</button>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="slip-btn print" onClick={handlePrint}>🖨️ Print / Download PDF</button>
            <button className="slip-btn whatsapp" onClick={handleWhatsApp}>💬 Share on WhatsApp</button>
          </div>
        </div>

        <div ref={slipRef}>
          <div className="slip-header">
            <h1>🏢 Attendance System</h1>
            <p>Salary Slip — {monthName}</p>
          </div>

          <div className="slip-info">
            <div className="slip-info-item"><label>Employee Name</label><span>{user.name}</span></div>
            <div className="slip-info-item"><label>Employee Code</label><span>#{user.employeeCode}</span></div>
            <div className="slip-info-item"><label>Role</label><span style={{ textTransform: "capitalize" }}>{user.role}</span></div>
            <div className="slip-info-item"><label>Salary / Day</label><span>Rs. {user.salaryPerDay || 500}</span></div>
            <div className="slip-info-item"><label>Month</label><span>{monthName}</span></div>
            <div className="slip-info-item"><label>Days Present</label><span>{attendance.length} days</span></div>
          </div>

          {attendance.length > 0 && (
            <table>
              <thead>
                <tr><th>#</th><th>Date</th><th>Check-In Time</th><th>Earned</th></tr>
              </thead>
              <tbody>
                {attendance.map((a, i) => (
                  <tr key={i}>
                    <td>{i + 1}</td>
                    <td>{a.date}</td>
                    <td>{a.checkInTime}</td>
                    <td className="green">Rs. {a.salaryEarned}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          <div className="slip-summary">
            <div className="slip-summary-row"><span>Total Days Present</span><span>{attendance.length} days</span></div>
            <div className="slip-summary-row"><span>Total Earned</span><span className="green">Rs. {totalEarned.toLocaleString()}</span></div>
            <div className="slip-summary-row"><span>Salary Paid</span><span className="green">Rs. {totalPaid.toLocaleString()}</span></div>
            <div className="slip-summary-row total"><span>Pending Amount</span><span className="orange">Rs. {pending.toLocaleString()}</span></div>
          </div>

          <div className="slip-footer">
            <p>Generated on {new Date().toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" })}</p>
            <p>This is a computer-generated salary slip.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
